### ISSUE TITLE
Svg Slides image

### ISSUE THREAD

**Issue by itsJess1ca** [kentcdodds/custom-badges#1]
I'm not familiar with github enough yet to do a pull request confidently, however I've forked this project to [here](https://github.com/j3ddesign/custom-badges) to add an svg version of the image instead :)

Hope this helps! Let me know if you need me to run a PR or something ;)

**Comment by kentcdodds** [comment]
Thanks! Do you think you could update it a bit to look more like the other badges on [shields.io](http://shields.io/)? The font looks a little different for example.

**Comment by itsJess1ca** [comment]
Sure I'll take a look!

**Comment by itsJess1ca** [comment]
I've just pushed a new version thats a closer match to the shields.io badges

**Comment by kentcdodds** [comment]
Looks closer! But I think that the font fo the shields.io badges is a little more bold.

**Comment by itsJess1ca** [comment]
ah hah! I found the font they were using so it's near enough a straight match now, or as close as I could get it, atleast.

**Comment by kentcdodds** [comment]
Cool, getting better! See: https://github.com/j3ddesign/custom-badges/pull/1

**Comment by itsJess1ca** [comment]
that helped a bunch, Apparently I was using the wrong font all along. It's switched now and matches the badge you showed in that PR.

edit: Fixed positioning and font to match sheilds.io fully

**Comment by kentcdodds** [comment]
It's getting soooo close! Thank you for iterating on this with me :D

Here's how they compare:

[yours](https://rawgit.com/j3ddesign/custom-badges/master/badges/slides.svg)

<img width="395" alt="screen shot 2016-08-04 at 7 26 55 am" src="https://cloud.githubusercontent.com/assets/1500684/17403438/f1178444-5a14-11e6-9c46-a6ee0f449538.png">

[slides.io](https://img.shields.io/badge/xxx-slides-E5637C.svg?style=flat-square)

<img width="377" alt="screen shot 2016-08-04 at 7 26 49 am" src="https://cloud.githubusercontent.com/assets/1500684/17403441/f40854c6-5a14-11e6-9b52-ab946e7de8dc.png">

If you look reeeally closely, you can see that the word `slides` in yours is a little high vertically. I measured and it looks like the shields.io has the same space between the top of the `d` and the top of the badge and the bottom of the `d` and the bottom of the badge.

Also, could you make the slides logo more center? And it likely doesn't need quite as much space on its side. Check the space from the left of the badge to the left of the first `x` and the right of the dark space to the right of the last `x`.

This is so awesome that you're doing this. I can't wait to use it!

**Comment by itsJess1ca** [comment]
It's my pleasure :) I like to help where I can!

It's a perfect match now :+1:

**Comment by kentcdodds** [comment]
Awesome! It's perfect! Thanks for making this. I'm excited to merge it.

You mentioned

> I'm not familiar with github enough yet to do a pull request confidently

So you may want to check [this](http://kcd.im/pull-request) out :)

Let me know if you need any help!

**Comment by itsJess1ca** [comment]
Thanks for working with me on my very first PR :+1: 
I'm glad I could help!
